# Main sops config
keys:
  # ---------------------------------------------------------------
  # 👤 Users (Admins)
  # ---------------------------------------------------------------
  - &krit age1qxyp5wzwhjs4tq633gtg2d25czdgwf6rxuppasshgf4mhlu37etq909x6t

  # ---------------------------------------------------------------
  # 🖥️ Hosts (Machines)
  # ---------------------------------------------------------------
  - &nixos-desktop age1nvr3ges07kcl6h4lmmfl23lc07rl7njq9seyl4hp7uut4k8v53qquhfugp
  # - &nixos-laptop

creation_rules:
  # ---------------------------------------------------------------
  # 🔒 Secrets for "nixos-desktop"
  # Any file inside hosts/nixos-desktop/ ending in secrets-sops.yaml will use these keys
  # ---------------------------------------------------------------
  - path_regex: hosts/nixos-desktop/.*secrets-sops\.yaml$
    key_groups:
      - age:
          - *krit # You can decrypt (user "krit")
          - *nixos-desktop # The machine can decrypt (hostname "nixos-desktop")

  # ---------------------------------------------------------------
  # 🔒 Common rules for user "krit"
  # Matches any "krit-common-secrets-sops.yaml" inside the "common" folder
  # ---------------------------------------------------------------
  - path_regex: common/krit/sops/krit-common-secrets-sops.yaml$
    key_groups:
      - age:
          - *krit # You can decrypt (user krit)
          - *nixos-desktop # Desktop (nixos-desktop)
          # - *nixos_laptop # Laptop (nixos-laptop)

  # 🔒 (Example) Rules for a future host
  # ---------------------------------------------------------------
  # ---------------------------------------------------------------
  # - path_regex: hosts/francesco-desktop/.*secrets\.yaml$
  #   key_groups:
  #     - age:
  #         - *francesco
  #         - *francesco-desktop
